//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BZafEntities : DbContext
    {
        public BZafEntities()
            : base("name=BZafEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbm_Emp> tbm_Emp { get; set; }
        public virtual DbSet<tbm_Hor> tbm_Hor { get; set; }
        public virtual DbSet<tbm_Loc> tbm_Loc { get; set; }
        public virtual DbSet<tbm_Res> tbm_Res { get; set; }
        public virtual DbSet<tbm_Ser> tbm_Ser { get; set; }
        public virtual DbSet<tbm_Tra> tbm_Tra { get; set; }
        public virtual DbSet<tbm_Usr> tbm_Usr { get; set; }
    }
}
