//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbm_Res
    {
        public int co_emp { get; set; }
        public int co_loc { get; set; }
        public int co_res { get; set; }
        public Nullable<int> co_usr { get; set; }
        public Nullable<int> co_tra { get; set; }
        public Nullable<int> co_ser { get; set; }
        public Nullable<System.DateTime> fe_res { get; set; }
        public string st_reg { get; set; }
    
        public virtual tbm_Emp tbm_Emp { get; set; }
        public virtual tbm_Loc tbm_Loc { get; set; }
        public virtual tbm_Usr tbm_Usr { get; set; }
        public virtual tbm_Tra tbm_Tra { get; set; }
        public virtual tbm_Ser tbm_Ser { get; set; }
    }
}
