//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbm_usu
    {
        public int co_usr { get; set; }
        public string tx_nom { get; set; }
        public string tx_ape { get; set; }
        public string tx_tel { get; set; }
        public string tx_dir { get; set; }
    }
}
